insert into public.proverbs (canonical_text, normalized_text)
values
  ('Als de kat van huis is, dansen de muizen op tafel', public.normalize_phrase('Als de kat van huis is, dansen de muizen op tafel')),
  ('Als twee honden vechten om een been, loopt de derde ermee heen', public.normalize_phrase('Als twee honden vechten om een been, loopt de derde ermee heen')),
  ('Baat het niet, dan schaadt het niet', public.normalize_phrase('Baat het niet, dan schaadt het niet')),
  ('Boter bij de vis', public.normalize_phrase('Boter bij de vis')),
  ('De dorst lessen', public.normalize_phrase('De dorst lessen')),
  ('De appel valt niet ver van de boom', public.normalize_phrase('De appel valt niet ver van de boom')),
  ('De kogel is door de kerk', public.normalize_phrase('De kogel is door de kerk')),
  ('De maat is vol', public.normalize_phrase('De maat is vol')),
  ('De plank misslaan', public.normalize_phrase('De plank misslaan')),
  ('De tering naar de nering zetten', public.normalize_phrase('De tering naar de nering zetten')),
  ('De waarheid in pacht hebben', public.normalize_phrase('De waarheid in pacht hebben')),
  ('De wind van voren krijgen', public.normalize_phrase('De wind van voren krijgen')),
  ('Door de bomen het bos niet meer zien', public.normalize_phrase('Door de bomen het bos niet meer zien')),
  ('Een blauwtje lopen', public.normalize_phrase('Een blauwtje lopen')),
  ('Een druppel op een gloeiende plaat', public.normalize_phrase('Een druppel op een gloeiende plaat')),
  ('Een gegeven paard niet in de bek kijken', public.normalize_phrase('Een gegeven paard niet in de bek kijken')),
  ('Een knuppel in het hoenderhok gooien', public.normalize_phrase('Een knuppel in het hoenderhok gooien')),
  ('Een koekje van eigen deeg', public.normalize_phrase('Een koekje van eigen deeg')),
  ('Een oogje in het zeil houden', public.normalize_phrase('Een oogje in het zeil houden')),
  ('Een slag om de arm houden', public.normalize_phrase('Een slag om de arm houden')),
  ('Een storm in een glas water', public.normalize_phrase('Een storm in een glas water')),
  ('Ergens geen kaas van gegeten hebben', public.normalize_phrase('Ergens geen kaas van gegeten hebben')),
  ('Ergens met de pet naar gooien', public.normalize_phrase('Ergens met de pet naar gooien')),
  ('Het dak gaat eraf', public.normalize_phrase('Het dak gaat eraf')),
  ('Het is koek en ei', public.normalize_phrase('Het is koek en ei')),
  ('Het loopt in de soep', public.normalize_phrase('Het loopt in de soep')),
  ('Het water loopt me in de mond', public.normalize_phrase('Het water loopt me in de mond')),
  ('Hoge bomen vangen veel wind', public.normalize_phrase('Hoge bomen vangen veel wind')),
  ('Iemand blij maken met een dode mus', public.normalize_phrase('Iemand blij maken met een dode mus')),
  ('Iemand op de hak nemen', public.normalize_phrase('Iemand op de hak nemen')),
  ('Iemand op de vingers tikken', public.normalize_phrase('Iemand op de vingers tikken')),
  ('Iemand uit de tent lokken', public.normalize_phrase('Iemand uit de tent lokken')),
  ('Iets onder de knie hebben', public.normalize_phrase('Iets onder de knie hebben')),
  ('Iets uit de duim zuigen', public.normalize_phrase('Iets uit de duim zuigen')),
  ('Je hoofd boven water houden', public.normalize_phrase('Je hoofd boven water houden')),
  ('Je kunt niet alles hebben', public.normalize_phrase('Je kunt niet alles hebben')),
  ('Je laatste loodjes', public.normalize_phrase('Je laatste loodjes')),
  ('Je neus in andermans zaken steken', public.normalize_phrase('Je neus in andermans zaken steken')),
  ('Kaf van het koren scheiden', public.normalize_phrase('Kaf van het koren scheiden')),
  ('Kort maar krachtig', public.normalize_phrase('Kort maar krachtig')),
  ('Met de deur in huis vallen', public.normalize_phrase('Met de deur in huis vallen')),
  ('Met de mond vol tanden staan', public.normalize_phrase('Met de mond vol tanden staan')),
  ('Met de noorderzon vertrekken', public.normalize_phrase('Met de noorderzon vertrekken')),
  ('Nu komt de aap uit de mouw', public.normalize_phrase('Nu komt de aap uit de mouw')),
  ('Onder invloed zijn', public.normalize_phrase('Onder invloed zijn')),
  ('Oost west, thuis best', public.normalize_phrase('Oost west, thuis best')),
  ('Op de bonnefooi', public.normalize_phrase('Op de bonnefooi')),
  ('Op de valreep', public.normalize_phrase('Op de valreep')),
  ('Op hete kolen zitten', public.normalize_phrase('Op hete kolen zitten')),
  ('Over de schreef gaan', public.normalize_phrase('Over de schreef gaan')),
  ('Over koetjes en kalfjes praten', public.normalize_phrase('Over koetjes en kalfjes praten')),
  ('Spijkers op laag water zoeken', public.normalize_phrase('Spijkers op laag water zoeken')),
  ('Te diep in het glaasje hebben gekeken', public.normalize_phrase('Te diep in het glaasje hebben gekeken')),
  ('Tegen de bierkaai vechten', public.normalize_phrase('Tegen de bierkaai vechten')),
  ('Twee vliegen in een klap', public.normalize_phrase('Twee vliegen in een klap')),
  ('Uit een ander vaatje tappen', public.normalize_phrase('Uit een ander vaatje tappen')),
  ('Van de ene verbazing in de andere vallen', public.normalize_phrase('Van de ene verbazing in de andere vallen')),
  ('Van een koude kermis thuiskomen', public.normalize_phrase('Van een koude kermis thuiskomen')),
  ('Van een leien dakje gaan', public.normalize_phrase('Van een leien dakje gaan')),
  ('Van een mug een olifant maken', public.normalize_phrase('Van een mug een olifant maken')),
  ('Veel noten op je zang hebben', public.normalize_phrase('Veel noten op je zang hebben')),
  ('Voor een dubbeltje op de eerste rang zitten', public.normalize_phrase('Voor een dubbeltje op de eerste rang zitten')),
  ('Water bij de wijn doen', public.normalize_phrase('Water bij de wijn doen')),
  ('Water naar de zee dragen', public.normalize_phrase('Water naar de zee dragen')),
  ('Wie het kleine niet eert, is het grote niet weerd', public.normalize_phrase('Wie het kleine niet eert, is het grote niet weerd')),
  ('Wie het laatst lacht, lacht het best', public.normalize_phrase('Wie het laatst lacht, lacht het best')),
  ('Wie zijn billen brandt, moet op de blaren zitten', public.normalize_phrase('Wie zijn billen brandt, moet op de blaren zitten')),
  ('Zo dronken als een tor', public.normalize_phrase('Zo dronken als een tor')),
  ('Zo klaar als een klontje', public.normalize_phrase('Zo klaar als een klontje')),
  ('Zo vrij als een vogel', public.normalize_phrase('Zo vrij als een vogel'))
on conflict (normalized_text) do nothing;
