insert into public.proverbs (canonical_text, normalized_text)
values
  ('Achter de feiten aanlopen', public.normalize_phrase('Achter de feiten aanlopen')),
  ('Alle ballen in de lucht houden', public.normalize_phrase('Alle ballen in de lucht houden')),
  ('Als puntje bij paaltje komt', public.normalize_phrase('Als puntje bij paaltje komt')),
  ('Als sardientjes in een blik zitten', public.normalize_phrase('Als sardientjes in een blik zitten')),
  ('Beter ten halve gekeerd dan ten hele gedwaald', public.normalize_phrase('Beter ten halve gekeerd dan ten hele gedwaald')),
  ('Binnen de perken blijven', public.normalize_phrase('Binnen de perken blijven')),
  ('Dat zet geen zoden aan de dijk', public.normalize_phrase('Dat zet geen zoden aan de dijk')),
  ('De buit binnen hebben', public.normalize_phrase('De buit binnen hebben')),
  ('De handdoek in de ring gooien', public.normalize_phrase('De handdoek in de ring gooien')),
  ('De kar trekken', public.normalize_phrase('De kar trekken')),
  ('De lakens uitdelen', public.normalize_phrase('De lakens uitdelen')),
  ('De lont in het kruitvat steken', public.normalize_phrase('De lont in het kruitvat steken')),
  ('De touwtjes in handen hebben', public.normalize_phrase('De touwtjes in handen hebben')),
  ('De vingers aan iets branden', public.normalize_phrase('De vingers aan iets branden')),
  ('De zaak op scherp zetten', public.normalize_phrase('De zaak op scherp zetten')),
  ('Driemaal is scheepsrecht', public.normalize_phrase('Driemaal is scheepsrecht')),
  ('Een frisse wind laten waaien', public.normalize_phrase('Een frisse wind laten waaien')),
  ('Een gat in de lucht springen', public.normalize_phrase('Een gat in de lucht springen')),
  ('Een kat in de zak kopen', public.normalize_phrase('Een kat in de zak kopen')),
  ('Een schot in de roos', public.normalize_phrase('Een schot in de roos')),
  ('Een wit voetje halen', public.normalize_phrase('Een wit voetje halen')),
  ('Er geen gras over laten groeien', public.normalize_phrase('Er geen gras over laten groeien')),
  ('Er met de pet naar gooien', public.normalize_phrase('Er met de pet naar gooien')),
  ('Er middenin zitten', public.normalize_phrase('Er middenin zitten')),
  ('Er op of er onder', public.normalize_phrase('Er op of er onder')),
  ('Er warmpjes bij zitten', public.normalize_phrase('Er warmpjes bij zitten')),
  ('Geen blad voor de mond nemen', public.normalize_phrase('Geen blad voor de mond nemen')),
  ('Geen poot om op te staan hebben', public.normalize_phrase('Geen poot om op te staan hebben')),
  ('Geen speld tussen te krijgen', public.normalize_phrase('Geen speld tussen te krijgen')),
  ('Geen vuiltje aan de lucht', public.normalize_phrase('Geen vuiltje aan de lucht')),
  ('Het achterste van je tong niet laten zien', public.normalize_phrase('Het achterste van je tong niet laten zien')),
  ('Het hoofd koel houden', public.normalize_phrase('Het hoofd koel houden')),
  ('Het kaf van het koren scheiden', public.normalize_phrase('Het kaf van het koren scheiden')),
  ('Het mes snijdt aan twee kanten', public.normalize_phrase('Het mes snijdt aan twee kanten')),
  ('Het onderspit delven', public.normalize_phrase('Het onderspit delven')),
  ('Het over een andere boeg gooien', public.normalize_phrase('Het over een andere boeg gooien')),
  ('Het roer omgooien', public.normalize_phrase('Het roer omgooien')),
  ('Het schip in gaan', public.normalize_phrase('Het schip in gaan')),
  ('Het tij keren', public.normalize_phrase('Het tij keren')),
  ('Het vuur aan de schenen leggen', public.normalize_phrase('Het vuur aan de schenen leggen')),
  ('Iemand de loef afsteken', public.normalize_phrase('Iemand de loef afsteken')),
  ('Iemand de pas afsnijden', public.normalize_phrase('Iemand de pas afsnijden')),
  ('Iemand een hak zetten', public.normalize_phrase('Iemand een hak zetten')),
  ('Iemand over het hoofd zien', public.normalize_phrase('Iemand over het hoofd zien')),
  ('Iets aan de grote klok hangen', public.normalize_phrase('Iets aan de grote klok hangen')),
  ('Iets met beide handen aangrijpen', public.normalize_phrase('Iets met beide handen aangrijpen')),
  ('Je kaarten tegen de borst houden', public.normalize_phrase('Je kaarten tegen de borst houden')),
  ('Je kroon spannen', public.normalize_phrase('Je kroon spannen')),
  ('Je slag slaan', public.normalize_phrase('Je slag slaan')),
  ('Je tanden ergens in zetten', public.normalize_phrase('Je tanden ergens in zetten')),
  ('Je tijd verdoen', public.normalize_phrase('Je tijd verdoen')),
  ('Kort en goed', public.normalize_phrase('Kort en goed')),
  ('Koren op de molen zijn', public.normalize_phrase('Koren op de molen zijn')),
  ('Met beide benen op de grond staan', public.normalize_phrase('Met beide benen op de grond staan')),
  ('Met hangende pootjes terugkomen', public.normalize_phrase('Met hangende pootjes terugkomen')),
  ('Met open armen ontvangen', public.normalize_phrase('Met open armen ontvangen')),
  ('Nattevingerwerk', public.normalize_phrase('Nattevingerwerk')),
  ('Niet over een nacht ijs gaan', public.normalize_phrase('Niet over een nacht ijs gaan')),
  ('Nog niet droog achter de oren zijn', public.normalize_phrase('Nog niet droog achter de oren zijn')),
  ('Om den brode', public.normalize_phrase('Om den brode')),
  ('Onder een hoedje spelen', public.normalize_phrase('Onder een hoedje spelen')),
  ('Onder stoom staan', public.normalize_phrase('Onder stoom staan')),
  ('Op eieren lopen', public.normalize_phrase('Op eieren lopen')),
  ('Op rozen zitten', public.normalize_phrase('Op rozen zitten')),
  ('Over lijken gaan', public.normalize_phrase('Over lijken gaan')),
  ('Overstag gaan', public.normalize_phrase('Overstag gaan')),
  ('Oud zeer oprakelen', public.normalize_phrase('Oud zeer oprakelen')),
  ('Recht door zee zijn', public.normalize_phrase('Recht door zee zijn')),
  ('Rozengeur en maneschijn', public.normalize_phrase('Rozengeur en maneschijn')),
  ('Twee handen op een buik zijn', public.normalize_phrase('Twee handen op een buik zijn')),
  ('Van alle markten thuis zijn', public.normalize_phrase('Van alle markten thuis zijn')),
  ('Van de regen in de drup komen', public.normalize_phrase('Van de regen in de drup komen')),
  ('Van dik hout zaagt men planken', public.normalize_phrase('Van dik hout zaagt men planken')),
  ('Van goeden huize komen', public.normalize_phrase('Van goeden huize komen')),
  ('Van wal steken', public.normalize_phrase('Van wal steken')),
  ('Veel water door de zee zien stromen', public.normalize_phrase('Veel water door de zee zien stromen')),
  ('Voet bij stuk houden', public.normalize_phrase('Voet bij stuk houden')),
  ('Voor Pampus liggen', public.normalize_phrase('Voor Pampus liggen')),
  ('Voor schut staan', public.normalize_phrase('Voor schut staan')),
  ('Waar het schip strandt, spoelt van alles aan', public.normalize_phrase('Waar het schip strandt, spoelt van alles aan')),
  ('Wind in de zeilen hebben', public.normalize_phrase('Wind in de zeilen hebben')),
  ('Zeilen bijzetten', public.normalize_phrase('Zeilen bijzetten')),
  ('Zijn schip achter zich verbranden', public.normalize_phrase('Zijn schip achter zich verbranden')),
  ('Zout in de wond strooien', public.normalize_phrase('Zout in de wond strooien')),
  ('Aan lager wal raken', public.normalize_phrase('Aan lager wal raken')),
  ('Aan hetzelfde touw trekken', public.normalize_phrase('Aan hetzelfde touw trekken')),
  ('Alle hens aan dek', public.normalize_phrase('Alle hens aan dek')),
  ('Bakzeil halen', public.normalize_phrase('Bakzeil halen')),
  ('De boot afhouden', public.normalize_phrase('De boot afhouden')),
  ('De boot missen', public.normalize_phrase('De boot missen')),
  ('De koers kwijt zijn', public.normalize_phrase('De koers kwijt zijn')),
  ('De klippen omzeilen', public.normalize_phrase('De klippen omzeilen')),
  ('De lading dekt de vlag niet', public.normalize_phrase('De lading dekt de vlag niet')),
  ('De mast opgaan', public.normalize_phrase('De mast opgaan')),
  ('De riemen gebruiken die je hebt', public.normalize_phrase('De riemen gebruiken die je hebt')),
  ('De veilige haven bereiken', public.normalize_phrase('De veilige haven bereiken')),
  ('Een behouden vaart', public.normalize_phrase('Een behouden vaart')),
  ('Een vlag die de lading dekt', public.normalize_phrase('Een vlag die de lading dekt')),
  ('Een oude rot in het vak', public.normalize_phrase('Een oude rot in het vak')),
  ('Geen schip zonder schrammen', public.normalize_phrase('Geen schip zonder schrammen')),
  ('Het anker uitgooien', public.normalize_phrase('Het anker uitgooien')),
  ('Het roer recht houden', public.normalize_phrase('Het roer recht houden')),
  ('Iemand kielhalen', public.normalize_phrase('Iemand kielhalen')),
  ('Iemand in het kielzog volgen', public.normalize_phrase('Iemand in het kielzog volgen')),
  ('In iemands vaarwater zitten', public.normalize_phrase('In iemands vaarwater zitten')),
  ('Koers zetten naar beter weer', public.normalize_phrase('Koers zetten naar beter weer')),
  ('Met man en macht', public.normalize_phrase('Met man en macht')),
  ('Niet in hetzelfde schuitje zitten', public.normalize_phrase('Niet in hetzelfde schuitje zitten')),
  ('Op goed geluk varen', public.normalize_phrase('Op goed geluk varen')),
  ('Op de golven van het geluk drijven', public.normalize_phrase('Op de golven van het geluk drijven')),
  ('Op het droge zitten', public.normalize_phrase('Op het droge zitten')),
  ('Op ramkoers liggen', public.normalize_phrase('Op ramkoers liggen')),
  ('Schip ahoi', public.normalize_phrase('Schip ahoi')),
  ('Tussen wal en schip vallen', public.normalize_phrase('Tussen wal en schip vallen')),
  ('Uit dezelfde haven komen', public.normalize_phrase('Uit dezelfde haven komen')),
  ('Uit de wind blijven', public.normalize_phrase('Uit de wind blijven')),
  ('Van de wal in de sloot raken', public.normalize_phrase('Van de wal in de sloot raken')),
  ('Voor anker gaan', public.normalize_phrase('Voor anker gaan')),
  ('Water maken', public.normalize_phrase('Water maken')),
  ('Zo lek als een mandje zijn', public.normalize_phrase('Zo lek als een mandje zijn')),
  ('Aan de zwier zijn', public.normalize_phrase('Aan de zwier zijn')),
  ('Bij de pakken neerzitten', public.normalize_phrase('Bij de pakken neerzitten')),
  ('Dat is gesneden koek', public.normalize_phrase('Dat is gesneden koek')),
  ('De geest krijgen', public.normalize_phrase('De geest krijgen')),
  ('De remmen losgooien', public.normalize_phrase('De remmen losgooien')),
  ('De smaak te pakken hebben', public.normalize_phrase('De smaak te pakken hebben')),
  ('Er een klap op geven', public.normalize_phrase('Er een klap op geven')),
  ('Er een schepje bovenop doen', public.normalize_phrase('Er een schepje bovenop doen')),
  ('Ergens brood in zien', public.normalize_phrase('Ergens brood in zien')),
  ('Hak op de tak springen', public.normalize_phrase('Hak op de tak springen')),
  ('Het feest kan beginnen', public.normalize_phrase('Het feest kan beginnen')),
  ('Iets wegspoelen', public.normalize_phrase('Iets wegspoelen')),
  ('Met de billen bloot gaan', public.normalize_phrase('Met de billen bloot gaan')),
  ('Met droge ogen liegen', public.normalize_phrase('Met droge ogen liegen')),
  ('Met een slok op', public.normalize_phrase('Met een slok op')),
  ('Niet vies zijn van een borrel', public.normalize_phrase('Niet vies zijn van een borrel')),
  ('Onder zeil zijn', public.normalize_phrase('Onder zeil zijn')),
  ('Op de bar klimmen', public.normalize_phrase('Op de bar klimmen')),
  ('Op stap zijn', public.normalize_phrase('Op stap zijn')),
  ('Over de tong gaan', public.normalize_phrase('Over de tong gaan')),
  ('Tot in de kleine uurtjes doorgaan', public.normalize_phrase('Tot in de kleine uurtjes doorgaan')),
  ('Uit de bocht vliegen', public.normalize_phrase('Uit de bocht vliegen')),
  ('Uit het veld geslagen zijn', public.normalize_phrase('Uit het veld geslagen zijn')),
  ('Vol goede moed', public.normalize_phrase('Vol goede moed')),
  ('Voor de draad ermee komen', public.normalize_phrase('Voor de draad ermee komen')),
  ('Waar het hart vol van is, loopt de mond van over', public.normalize_phrase('Waar het hart vol van is, loopt de mond van over')),
  ('Zich uit de naad werken', public.normalize_phrase('Zich uit de naad werken'))
on conflict (normalized_text) do nothing;
