insert into public.proverbs (canonical_text, normalized_text)
values
  ('Er geen kaas van gegeten hebben', public.normalize_phrase('Er geen kaas van gegeten hebben')),
  ('Van twee walletjes eten', public.normalize_phrase('Van twee walletjes eten')),
  ('Appels met peren vergelijken', public.normalize_phrase('Appels met peren vergelijken')),
  ('Verandering van spijs doet eten', public.normalize_phrase('Verandering van spijs doet eten')),
  ('Met grote heren is het kwaad kersen eten', public.normalize_phrase('Met grote heren is het kwaad kersen eten')),
  ('Beter een vogel in de hand dan tien in de lucht', public.normalize_phrase('Beter een vogel in de hand dan tien in de lucht')),
  ('Een ezel stoot zich geen twee keer aan dezelfde steen', public.normalize_phrase('Een ezel stoot zich geen twee keer aan dezelfde steen')),
  ('Het is water naar de zee dragen', public.normalize_phrase('Het is water naar de zee dragen')),
  ('Wie wind zaait, zal storm oogsten', public.normalize_phrase('Wie wind zaait, zal storm oogsten')),
  ('Het gras is groener bij de buren', public.normalize_phrase('Het gras is groener bij de buren')),
  ('De laatste loodjes wegen het zwaarst', public.normalize_phrase('De laatste loodjes wegen het zwaarst')),
  ('Gooi nooit oude schoenen weg voordat je nieuwe hebt', public.normalize_phrase('Gooi nooit oude schoenen weg voordat je nieuwe hebt')),
  ('De beste stuurlui staan aan wal', public.normalize_phrase('De beste stuurlui staan aan wal')),
  ('Een goed verstaander heeft maar een half woord nodig', public.normalize_phrase('Een goed verstaander heeft maar een half woord nodig')),
  ('De ene hand wast de andere', public.normalize_phrase('De ene hand wast de andere')),
  ('Al is de leugen nog zo snel, de waarheid achterhaalt hem wel', public.normalize_phrase('Al is de leugen nog zo snel, de waarheid achterhaalt hem wel')),
  ('Wie zijn neus schendt, schendt zijn aangezicht', public.normalize_phrase('Wie zijn neus schendt, schendt zijn aangezicht')),
  ('Haastige spoed is zelden goed', public.normalize_phrase('Haastige spoed is zelden goed')),
  ('Oude koeien uit de sloot halen', public.normalize_phrase('Oude koeien uit de sloot halen')),
  ('Iemand in de kou laten staan', public.normalize_phrase('Iemand in de kou laten staan')),
  ('Zoals de waard is, vertrouwt hij zijn gasten', public.normalize_phrase('Zoals de waard is, vertrouwt hij zijn gasten')),
  ('Een speld in een hooiberg zoeken', public.normalize_phrase('Een speld in een hooiberg zoeken')),
  ('Over smaak valt niet te twisten', public.normalize_phrase('Over smaak valt niet te twisten')),
  ('Met een schone lei beginnen', public.normalize_phrase('Met een schone lei beginnen')),
  ('Het is een gebed zonder eind', public.normalize_phrase('Het is een gebed zonder eind')),
  ('Geen nieuws is goed nieuws', public.normalize_phrase('Geen nieuws is goed nieuws')),
  ('De waarheid komt altijd boven water', public.normalize_phrase('De waarheid komt altijd boven water')),
  ('In het land der blinden is eenoog koning', public.normalize_phrase('In het land der blinden is eenoog koning')),
  ('Het paard achter de wagen spannen', public.normalize_phrase('Het paard achter de wagen spannen')),
  ('Een mens lijdt het meest door het lijden dat hij vreest', public.normalize_phrase('Een mens lijdt het meest door het lijden dat hij vreest')),
  ('Van het concert des levens krijgt niemand een program', public.normalize_phrase('Van het concert des levens krijgt niemand een program')),
  ('Je moet het ijzer smeden als het heet is', public.normalize_phrase('Je moet het ijzer smeden als het heet is')),
  ('Wie zijn eigen nest bevuilt, moet erin liggen', public.normalize_phrase('Wie zijn eigen nest bevuilt, moet erin liggen')),
  ('Wie de bal kaatst, kan hem terugverwachten', public.normalize_phrase('Wie de bal kaatst, kan hem terugverwachten')),
  ('Achter de wolken schijnt de zon', public.normalize_phrase('Achter de wolken schijnt de zon')),
  ('Het bloed kruipt waar het niet gaan kan', public.normalize_phrase('Het bloed kruipt waar het niet gaan kan')),
  ('Op een droogje zitten', public.normalize_phrase('Op een droogje zitten')),
  ('De gifbeker leegdrinken', public.normalize_phrase('De gifbeker leegdrinken')),
  ('Iemand onder de tafel drinken', public.normalize_phrase('Iemand onder de tafel drinken')),
  ('Dat scheelt een slok op een borrel', public.normalize_phrase('Dat scheelt een slok op een borrel')),
  ('Hand in eigen boezem steken', public.normalize_phrase('Hand in eigen boezem steken'))
on conflict (normalized_text) do nothing;

