insert into public.proverbs (canonical_text, normalized_text)
values
  ('Wie A zegt, moet ook B zeggen', public.normalize_phrase('Wie A zegt, moet ook B zeggen')),
  ('De aanhouder wint', public.normalize_phrase('De aanhouder wint')),
  ('Niet geschoten is altijd mis', public.normalize_phrase('Niet geschoten is altijd mis')),
  ('Men moet zijn bed maken zoals men slapen wil', public.normalize_phrase('Men moet zijn bed maken zoals men slapen wil')),
  ('Belofte maakt schuld', public.normalize_phrase('Belofte maakt schuld')),
  ('Wat de boer niet kent, dat vreet hij niet', public.normalize_phrase('Wat de boer niet kent, dat vreet hij niet')),
  ('De eerste klap is een daalder waard', public.normalize_phrase('De eerste klap is een daalder waard')),
  ('Al doende leert men', public.normalize_phrase('Al doende leert men')),
  ('Eerlijkheid duurt het langst', public.normalize_phrase('Eerlijkheid duurt het langst')),
  ('Wie het eerst komt, die het eerst maalt', public.normalize_phrase('Wie het eerst komt, die het eerst maalt')),
  ('Gezelligheid kent geen tijd', public.normalize_phrase('Gezelligheid kent geen tijd')),
  ('Een ezel stoot zich in ''t gemeen geen twee keer aan dezelfde steen', public.normalize_phrase('Een ezel stoot zich in ''t gemeen geen twee keer aan dezelfde steen')),
  ('Voor geld kun je de duivel doen dansen', public.normalize_phrase('Voor geld kun je de duivel doen dansen')),
  ('Wie zijn gat brandt, moet op de blaren zitten', public.normalize_phrase('Wie zijn gat brandt, moet op de blaren zitten')),
  ('Een goed begin is het halve werk', public.normalize_phrase('Een goed begin is het halve werk')),
  ('Ieder huisje heeft zijn kruisje', public.normalize_phrase('Ieder huisje heeft zijn kruisje')),
  ('Eigen haard is goud waard', public.normalize_phrase('Eigen haard is goud waard')),
  ('Vele handen maken licht werk', public.normalize_phrase('Vele handen maken licht werk')),
  ('Wie met honden omgaat, krijgt vlooien', public.normalize_phrase('Wie met honden omgaat, krijgt vlooien')),
  ('Men kan geen ijzer met handen breken', public.normalize_phrase('Men kan geen ijzer met handen breken')),
  ('Men moet het ijzer smeden als het heet is', public.normalize_phrase('Men moet het ijzer smeden als het heet is')),
  ('Jong geleerd, oud gedaan', public.normalize_phrase('Jong geleerd, oud gedaan')),
  ('De gestage jager wint', public.normalize_phrase('De gestage jager wint')),
  ('Als het kalf verdronken is, dempt men de put', public.normalize_phrase('Als het kalf verdronken is, dempt men de put')),
  ('Van een kale kip kun je niet plukken', public.normalize_phrase('Van een kale kip kun je niet plukken')),
  ('Zoals het klokje thuis tikt, tikt het nergens', public.normalize_phrase('Zoals het klokje thuis tikt, tikt het nergens')),
  ('Al is de leugen nog zo snel, de waarheid achterhaalt haar wel', public.normalize_phrase('Al is de leugen nog zo snel, de waarheid achterhaalt haar wel')),
  ('Zo lang er leven is, is er hoop', public.normalize_phrase('Zo lang er leven is, is er hoop')),
  ('Beter laat dan nooit', public.normalize_phrase('Beter laat dan nooit')),
  ('Een man een man, een woord een woord', public.normalize_phrase('Een man een man, een woord een woord')),
  ('Dat muisje krijgt nog wel een staartje', public.normalize_phrase('Dat muisje krijgt nog wel een staartje')),
  ('Nood breekt wet', public.normalize_phrase('Nood breekt wet')),
  ('Door het oog van de naald kruipen', public.normalize_phrase('Door het oog van de naald kruipen')),
  ('Onkruid vergaat niet', public.normalize_phrase('Onkruid vergaat niet')),
  ('Men moet een gegeven paard niet in de bek kijken', public.normalize_phrase('Men moet een gegeven paard niet in de bek kijken')),
  ('Waar rook is, is vuur', public.normalize_phrase('Waar rook is, is vuur')),
  ('Rome is niet in één dag gebouwd', public.normalize_phrase('Rome is niet in één dag gebouwd')),
  ('Er leiden meer wegen naar Rome', public.normalize_phrase('Er leiden meer wegen naar Rome')),
  ('Als er één schaap over de dam is, volgen er meer', public.normalize_phrase('Als er één schaap over de dam is, volgen er meer')),
  ('Wie de schoen past, trekke hem aan', public.normalize_phrase('Wie de schoen past, trekke hem aan')),
  ('Tijd is geld', public.normalize_phrase('Tijd is geld')),
  ('Van uitstel komt afstel', public.normalize_phrase('Van uitstel komt afstel')),
  ('Vertrouwen komt te voet en gaat te paard', public.normalize_phrase('Vertrouwen komt te voet en gaat te paard')),
  ('Wat in een goed vat zit, verzuurt niet', public.normalize_phrase('Wat in een goed vat zit, verzuurt niet')),
  ('Beter één vogel in de hand dan tien in de lucht', public.normalize_phrase('Beter één vogel in de hand dan tien in de lucht')),
  ('Wie niet waagt, die niet wint', public.normalize_phrase('Wie niet waagt, die niet wint')),
  ('Water loopt altijd naar de zee', public.normalize_phrase('Water loopt altijd naar de zee')),
  ('Goede wijn behoeft geen krans', public.normalize_phrase('Goede wijn behoeft geen krans')),
  ('Spreken is zilver, zwijgen is goud', public.normalize_phrase('Spreken is zilver, zwijgen is goud')),
  ('Zuinigheid met vlijt bouwt huizen als kastelen', public.normalize_phrase('Zuinigheid met vlijt bouwt huizen als kastelen')),
  ('Na regen komt zonneschijn', public.normalize_phrase('Na regen komt zonneschijn')),
  ('Om de hete brij heen draaien', public.normalize_phrase('Om de hete brij heen draaien')),
  ('Zoete broodjes bakken', public.normalize_phrase('Zoete broodjes bakken')),
  ('Geen deuk in een pakje boter schoppen', public.normalize_phrase('Geen deuk in een pakje boter schoppen')),
  ('Roet in het eten gooien', public.normalize_phrase('Roet in het eten gooien')),
  ('Voor een appel en een ei', public.normalize_phrase('Voor een appel en een ei')),
  ('Met de gebakken peren zitten', public.normalize_phrase('Met de gebakken peren zitten')),
  ('Dat is geen klein bier', public.normalize_phrase('Dat is geen klein bier')),
  ('Op een houtje bijten', public.normalize_phrase('Op een houtje bijten')),
  ('Het zal me worst wezen', public.normalize_phrase('Het zal me worst wezen')),
  ('Gaan met die banaan', public.normalize_phrase('Gaan met die banaan')),
  ('Zijn natje en zijn droogje lusten', public.normalize_phrase('Zijn natje en zijn droogje lusten')),
  ('Een stuk in de kraag drinken', public.normalize_phrase('Een stuk in de kraag drinken')),
  ('In de olie zijn', public.normalize_phrase('In de olie zijn')),
  ('Hansje in de kelder', public.normalize_phrase('Hansje in de kelder')),
  ('Vis moet zwemmen', public.normalize_phrase('Vis moet zwemmen')),
  ('Wat leven in de brouwerij brengen', public.normalize_phrase('Wat leven in de brouwerij brengen')),
  ('Een loden pijp hebben', public.normalize_phrase('Een loden pijp hebben')),
  ('Een kater hebben', public.normalize_phrase('Een kater hebben')),
  ('Als de drank is in de man, is de wijsheid in de kan', public.normalize_phrase('Als de drank is in de man, is de wijsheid in de kan')),
  ('Mosterd na de maaltijd', public.normalize_phrase('Mosterd na de maaltijd')),
  ('Met de neus in de boter vallen', public.normalize_phrase('Met de neus in de boter vallen')),
  ('De koek is op', public.normalize_phrase('De koek is op')),
  ('Het botert niet', public.normalize_phrase('Het botert niet')),
  ('De kers op de taart', public.normalize_phrase('De kers op de taart')),
  ('Een afzakkertje nemen', public.normalize_phrase('Een afzakkertje nemen')),
  ('Een glaasje op de valreep', public.normalize_phrase('Een glaasje op de valreep')),
  ('Op de fles zijn', public.normalize_phrase('Op de fles zijn')),
  ('Er verdrinken er meer in het glas dan in de zee', public.normalize_phrase('Er verdrinken er meer in het glas dan in de zee')),
  ('Zuipen als een ketter', public.normalize_phrase('Zuipen als een ketter')),
  ('Wie het onderste uit de kan wil hebben, krijgt het deksel op de neus', public.normalize_phrase('Wie het onderste uit de kan wil hebben, krijgt het deksel op de neus')),
  ('Wie boter op zijn hoofd heeft, moet niet in de zon lopen', public.normalize_phrase('Wie boter op zijn hoofd heeft, moet niet in de zon lopen')),
  ('De hond in de pot vinden', public.normalize_phrase('De hond in de pot vinden')),
  ('Met lange tanden eten', public.normalize_phrase('Met lange tanden eten')),
  ('Zien eten doet eten', public.normalize_phrase('Zien eten doet eten')),
  ('Oude wijn in nieuwe zakken', public.normalize_phrase('Oude wijn in nieuwe zakken')),
  ('De soep wordt niet zo heet gegeten als zij wordt opgediend', public.normalize_phrase('De soep wordt niet zo heet gegeten als zij wordt opgediend')),
  ('Dat is een eitje', public.normalize_phrase('Dat is een eitje')),
  ('Op de koffie komen', public.normalize_phrase('Op de koffie komen')),
  ('De bloemetjes buiten zetten', public.normalize_phrase('De bloemetjes buiten zetten')),
  ('Iets in kannen en kruiken hebben', public.normalize_phrase('Iets in kannen en kruiken hebben')),
  ('De proef op de som nemen', public.normalize_phrase('De proef op de som nemen')),
  ('De toon is gezet', public.normalize_phrase('De toon is gezet')),
  ('Het glas is halfvol', public.normalize_phrase('Het glas is halfvol'))
on conflict (normalized_text) do nothing;
